# QuickStatements v1 commands, generated by
# master_library_lod.wikidata_contribution. Review the matching
# proposals.md, delete lines you do not want, and import at
# https://quickstatements.toolforge.org under your own account.
# Never run unreviewed; you are accountable for every edit.

Q3020997|P856|"https://dechencholing.org"|S854|"https://dechencholing.org"
Q5520387|P6375|"432 Western Avenue"@en|S854|"http://gampoabbey.org"
Q5520387|P281|"B0E 2P0"|S854|"http://gampoabbey.org"
Q1034225|P6375|"45 Francis Avenue"@en|S854|"https://hds.harvard.edu"
Q1034225|P281|"02138"|S854|"https://hds.harvard.edu"
Q1270200|P6375|"Eskdalemuir, Langholm"@en|S854|"https://samyeling.org"
Q1270200|P281|"DG13 5QL"|S854|"https://samyeling.org"
Q977642|P856|"https://kagyu.org"|S854|"https://kagyu.org"
Q977642|P6375|"435 Meads Mountain Road"@en|S854|"https://kagyu.org"
Q977642|P281|"12409"|S854|"https://kagyu.org"
Q6372782|P856|"https://karmecholing.org"|S854|"https://karmecholing.org"
Q6372782|P6375|"494 U.S. Route 5 South"@en|S854|"https://karmecholing.org"
Q6372782|P281|"05821"|S854|"https://karmecholing.org"
Q7487466|P6375|"4961 County Road 68C"@en|S854|"https://www.dralamountain.org/"
Q7487466|P281|"80545"|S854|"https://www.dralamountain.org/"
